"""Expert Priority Order - Auto-generated by ECC TASK_003"""
# This file defines the expert priority order for the ensemble

EXPERT_PRIORITY_ORDER = [
    "AntiTrend",   # PRIMARY_EXPERT - highest marginal gain in ensemble
    "Trend",        # NOISE_EXPERT - but included for diversity
    "Color",        # SECONDARY_EXPERT
    "Gap",          # NOISE_EXPERT
    "Frequency",   # NOISE_EXPERT  
    "Cycle",        # NOISE_EXPERT
    "Momentum"      # NOISE_EXPERT - high individual hit but redundant
]

EXPERT_ROLES = {
    "AntiTrend": "PRIMARY_EXPERT",
    "Trend": "NOISE_EXPERT",
    "Color": "SECONDARY_EXPERT",
    "Gap": "NOISE_EXPERT",
    "Frequency": "NOISE_EXPERT",
    "Cycle": "NOISE_EXPERT",
    "Momentum": "NOISE_EXPERT"
}

# Experts that should potentially be dropped
NOISE_EXPERTS = ["Gap", "Trend", "Momentum", "Frequency", "Cycle"]

# Primary expert for ensemble
PRIMARY_EXPERT = "AntiTrend"

# Secondary experts
SECONDARY_EXPERTS = ["Color"]
